### ISSUE TITLE
Exported model with all animations is semi-corrupted

### ISSUE THREAD

**Issue by GrzybDev** [RatchetModding/Replanetizer#92]
Hello,

Thanks for amazing tool, I have one issue while using it - I'm trying to export Ratchet models with all animations as shown here:
![image](https://user-images.githubusercontent.com/58396043/232307877-25df0458-82f7-4fe0-a909-df6890c62fcc.png)

After importing this file in Blender, only first(?) animation works/is recognized:
![image](https://user-images.githubusercontent.com/58396043/232307919-b0352fe0-9f56-45cb-bf8d-26329da62f14.png)

Furthermore, importing file created with "All animations"/"Seperate file for each Animation" option in Unity straight up - doesn't work as shown here:
![image](https://user-images.githubusercontent.com/58396043/232308001-17578d8f-02a2-45c7-a97a-9de2e609bebc.png)

I can successfully import files to both Blender/Unity if they were created with "No Animations"/"Concatenate Animations" option.

Is this expected behaviour? And if so, what program should I use to correctly read dae file with multiple animations (And preferably convert it to something else) :)

**Comment by MilchRatchet** [comment]
Hi, 

Blender in combination with all animations not working as desired is expected behaviour that we couldn't get around yet. Essentially, Blender loads all animations but it treats them as all being one animation or something so that only the first pair of transformations (i.e. the first animation) is used.
So for Blender using the other two export modes is recommended currently.

We had not tested Unity to my knowledge so that not working is a bug we will need to look into. Thanks for the heads up.

Unfortunately, I think I can't name a program that correctly reads the multiple animations export correctly. The dae file format is a bit weird when it comes to those things hence we implemented the concatenated animations mode. I will test Unity and see if I can fix the errors and maybe if we are lucky Unity will work with the multiple animations export correctly.

**Comment by everelw** [comment]
Was running in to this issue as well. Tracking this.

**Comment by MilchRatchet** [comment]
To address this issue, Replanetizer now features a GLTF exporter which correctly exports all animations according to the GLTF specs. The "all animations" feature was removed from the collada exporter. If a different format than GLTF is desired, it is recommended to use tools like Blender to convert the GLTF file to the desired format.

I am closing this issue now, if issues regarding exporting all animations persist reopen this issue or create a new one.
